using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PlantApp.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddIsoFieldsToCountriesAndSeedData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "iso",
                table: "countries",
                type: "text",
                nullable: false);

            migrationBuilder.AddColumn<string>(
                name: "iso3",
                table: "countries",
                type: "text",
                nullable: false);

            migrationBuilder.AddColumn<int>(
                name: "phone_code",
                table: "countries",
                type: "integer",
                nullable: false);


            migrationBuilder.InsertData(
                table: "countries",
                columns: new[] { "id", "iso", "name", "iso3", "phone_code" },
                values: new object[,]
                {
                    { 1, "AF", "Afghanistan", "AFG", 93 },
                    { 2, "AL", "Albania", "ALB", 355 },
                    { 3, "DZ", "Algeria", "DZA", 213 },
                    { 4, "AS", "American Samoa", "ASM", 1684 },
                    { 5, "AD", "Andorra", "AND", 376 },
                    { 6, "AO", "Angola", "AGO", 244 },
                    { 7, "AI", "Anguilla", "AIA", 1264 },
                    { 8, "AQ", "Antarctica", "ATA", 0 },
                    { 9, "AG", "Antigua and Barbuda", "ATG", 1268 },
                    { 10, "AR", "Argentina", "ARG", 54 },
                    { 11, "AM", "Armenia", "ARM", 374 },
                    { 12, "AW", "Aruba", "ABW", 297 },
                    { 13, "AU", "Australia", "AUS", 61 },
                    { 14, "AT", "Austria", "AUT", 43 },
                    { 15, "AZ", "Azerbaijan", "AZE", 994 },
                    { 16, "BS", "Bahamas", "BHS", 1242 },
                    { 17, "BH", "Bahrain", "BHR", 973 },
                    { 18, "BD", "Bangladesh", "BGD", 880 },
                    { 19, "BB", "Barbados", "BRB", 1246 },
                    { 20, "BY", "Belarus", "BLR", 375 },
                    { 21, "BE", "Belgium", "BEL", 32 },
                    { 22, "BZ", "Belize", "BLZ", 501 },
                    { 23, "BJ", "Benin", "BEN", 229 },
                    { 24, "BM", "Bermuda", "BMU", 1441 },
                    { 25, "BT", "Bhutan", "BTN", 975 },
                    { 26, "BO", "Bolivia", "BOL", 591 },
                    { 27, "BQ", "Bonaire, Sint Eustatius and Saba", "BES", 599 },
                    { 28, "BA", "Bosnia and Herzegovina", "BIH", 387 },
                    { 29, "BW", "Botswana", "BWA", 267 },
                    { 30, "BV", "Bouvet Island", "BVT", 0 },
                    { 31, "BR", "Brazil", "BRA", 55 },
                    { 32, "IO", "British Indian Ocean Territory", "IOT", 246 },
                    { 33, "BN", "Brunei Darussalam", "BRN", 673 },
                    { 34, "BG", "Bulgaria", "BGR", 359 },
                    { 35, "BF", "Burkina Faso", "BFA", 226 },
                    { 36, "BI", "Burundi", "BDI", 257 },
                    { 37, "CV", "Cabo Verde", "CPV", 238 },
                    { 38, "KH", "Cambodia", "KHM", 855 },
                    { 39, "CM", "Cameroon", "CMR", 237 },
                    { 40, "CA", "Canada", "CAN", 1 },
                    { 41, "KY", "Cayman Islands", "CYM", 1345 },
                    { 42, "CF", "Central African Republic", "CAF", 236 },
                    { 43, "TD", "Chad", "TCD", 235 },
                    { 44, "CL", "Chile", "CHL", 56 },
                    { 45, "CN", "China", "CHN", 86 },
                    { 46, "CX", "Christmas Island", "CXR", 61 },
                    { 47, "CC", "Cocos (Keeling) Islands", "CCK", 61 },
                    { 48, "CO", "Colombia", "COL", 57 },
                    { 49, "KM", "Comoros", "COM", 269 },
                    { 50, "CG", "Congo", "COG", 242 },
                    { 51, "CD", "Congo, the Democratic Republic of the", "COD", 243 },
                    { 52, "CK", "Cook Islands", "COK", 682 },
                    { 53, "CR", "Costa Rica", "CRI", 506 },
                    { 54, "CI", "Côte d''Ivoire", "CIV", 225 },
                    { 55, "HR", "Croatia", "HRV", 385 },
                    { 56, "CU", "Cuba", "CUB", 53 },
                    { 57, "CW", "Curaçao", "CUW", 599 },
                    { 58, "CY", "Cyprus", "CYP", 357 },
                    { 59, "CZ", "Czechia", "CZE", 420 },
                    { 60, "DK", "Denmark", "DNK", 45 },
                    { 61, "DJ", "Djibouti", "DJI", 253 },
                    { 62, "DM", "Dominica", "DMA", 1767 },
                    { 63, "DO", "Dominican Republic", "DOM", 1809 },
                    { 64, "EC", "Ecuador", "ECU", 593 },
                    { 65, "EG", "Egypt", "EGY", 20 },
                    { 66, "SV", "El Salvador", "SLV", 503 },
                    { 67, "GQ", "Equatorial Guinea", "GNQ", 240 },
                    { 68, "ER", "Eritrea", "ERI", 291 },
                    { 69, "EE", "Estonia", "EST", 372 },
                    { 70, "SZ", "Eswatini", "SWZ", 268 },
                    { 71, "ET", "Ethiopia", "ETH", 251 },
                    { 72, "FK", "Falkland Islands (Malvinas)", "FLK", 500 },
                    { 73, "FO", "Faroe Islands", "FRO", 298 },
                    { 74, "FJ", "Fiji", "FJI", 679 },
                    { 75, "FI", "Finland", "FIN", 358 },
                    { 76, "FR", "France", "FRA", 33 },
                    { 77, "GF", "French Guiana", "GUF", 594 },
                    { 78, "PF", "French Polynesia", "PYF", 689 },
                    { 79, "TF", "French Southern Territories", "ATF", 0 },
                    { 80, "GA", "Gabon", "GAB", 241 },
                    { 81, "GM", "Gambia", "GMB", 220 },
                    { 82, "GE", "Georgia", "GEO", 995 },
                    { 83, "DE", "Germany", "DEU", 49 },
                    { 84, "GH", "Ghana", "GHA", 233 },
                    { 85, "GI", "Gibraltar", "GIB", 350 },
                    { 86, "GR", "Greece", "GRC", 30 },
                    { 87, "GL", "Greenland", "GRL", 299 },
                    { 88, "GD", "Grenada", "GRD", 1473 },
                    { 89, "GP", "Guadeloupe", "GLP", 590 },
                    { 90, "GU", "Guam", "GUM", 1671 },
                    { 91, "GT", "Guatemala", "GTM", 502 },
                    { 92, "GG", "Guernsey", "GGY", 44 },
                    { 93, "GN", "Guinea", "GIN", 224 },
                    { 94, "GW", "Guinea-Bissau", "GNB", 245 },
                    { 95, "GY", "Guyana", "GUY", 592 },
                    { 96, "HT", "Haiti", "HTI", 509 },
                    { 97, "HM", "Heard Island and McDonald Islands", "HMD", 0 },
                    { 98, "VA", "Holy See", "VAT", 379 },
                    { 99, "HN", "Honduras", "HND", 504 },
                    { 100, "HK", "Hong Kong", "HKG", 852 },
                    { 101, "HU", "Hungary", "HUN", 36 },
                    { 102, "IS", "Iceland", "ISL", 354 },
                    { 103, "IN", "India", "IND", 91 },
                    { 104, "ID", "Indonesia", "IDN", 62 },
                    { 105, "IR", "Iran, Islamic Republic of", "IRN", 98 },
                    { 106, "IQ", "Iraq", "IRQ", 964 },
                    { 107, "IE", "Ireland", "IRL", 353 },
                    { 108, "IM", "Isle of Man", "IMN", 44 },
                    { 109, "IL", "Israel", "ISR", 972 },
                    { 110, "IT", "Italy", "ITA", 39 },
                    { 111, "JM", "Jamaica", "JAM", 1876 },
                    { 112, "JP", "Japan", "JPN", 81 },
                    { 113, "JE", "Jersey", "JEY", 44 },
                    { 114, "JO", "Jordan", "JOR", 962 },
                    { 115, "KZ", "Kazakhstan", "KAZ", 7 },
                    { 116, "KE", "Kenya", "KEN", 254 },
                    { 117, "KI", "Kiribati", "KIR", 686 },
                    { 118, "KP", "Korea, Democratic People''s Republic of", "PRK", 850 },
                    { 119, "KR", "Korea, Republic of", "KOR", 82 },
                    { 120, "XK", "Kosovo", "XKX", 383 },
                    { 121, "KW", "Kuwait", "KWT", 965 },
                    { 122, "KG", "Kyrgyzstan", "KGZ", 996 },
                    { 123, "LA", "Lao People''s Democratic Republic", "LAO", 856 },
                    { 124, "LV", "Latvia", "LVA", 371 },
                    { 125, "LB", "Lebanon", "LBN", 961 },
                    { 126, "LS", "Lesotho", "LSO", 266 },
                    { 127, "LR", "Liberia", "LBR", 231 },
                    { 128, "LY", "Libya", "LBY", 218 },
                    { 129, "LI", "Liechtenstein", "LIE", 423 },
                    { 130, "LT", "Lithuania", "LTU", 370 },
                    { 131, "LU", "Luxembourg", "LUX", 352 },
                    { 132, "MO", "Macao", "MAC", 853 },
                    { 133, "MG", "Madagascar", "MDG", 261 },
                    { 134, "MW", "Malawi", "MWI", 265 },
                    { 135, "MY", "Malaysia", "MYS", 60 },
                    { 136, "MV", "Maldives", "MDV", 960 },
                    { 137, "ML", "Mali", "MLI", 223 },
                    { 138, "MT", "Malta", "MLT", 356 },
                    { 139, "MH", "Marshall Islands", "MHL", 692 },
                    { 140, "MQ", "Martinique", "MTQ", 596 },
                    { 141, "MR", "Mauritania", "MRT", 222 },
                    { 142, "MU", "Mauritius", "MUS", 230 },
                    { 143, "YT", "Mayotte", "MYT", 262 },
                    { 144, "MX", "Mexico", "MEX", 52 },
                    { 145, "FM", "Micronesia, Federated States of", "FSM", 691 },
                    { 146, "MD", "Moldova, Republic of", "MDA", 373 },
                    { 147, "MC", "Monaco", "MCO", 377 },
                    { 148, "MN", "Mongolia", "MNG", 976 },
                    { 149, "ME", "Montenegro", "MNE", 382 },
                    { 150, "MS", "Montserrat", "MSR", 1664 },
                    { 151, "MA", "Morocco", "MAR", 212 },
                    { 152, "MZ", "Mozambique", "MOZ", 258 },
                    { 153, "MM", "Myanmar", "MMR", 95 },
                    { 154, "NA", "Namibia", "NAM", 264 },
                    { 155, "NR", "Nauru", "NRU", 674 },
                    { 156, "NP", "Nepal", "NPL", 977 },
                    { 157, "NL", "Netherlands", "NLD", 31 },
                    { 158, "NC", "New Caledonia", "NCL", 687 },
                    { 159, "NZ", "New Zealand", "NZL", 64 },
                    { 160, "NI", "Nicaragua", "NIC", 505 },
                    { 161, "NE", "Niger", "NER", 227 },
                    { 162, "NG", "Nigeria", "NGA", 234 },
                    { 163, "NU", "Niue", "NIU", 683 },
                    { 164, "NF", "Norfolk Island", "NFK", 672 },
                    { 165, "MK", "North Macedonia", "MKD", 389 },
                    { 166, "MP", "Northern Mariana Islands", "MNP", 1670 },
                    { 167, "NO", "Norway", "NOR", 47 },
                    { 168, "OM", "Oman", "OMN", 968 },
                    { 169, "PK", "Pakistan", "PAK", 92 },
                    { 170, "PW", "Palau", "PLW", 680 },
                    { 171, "PS", "Palestine, State of", "PSE", 970 },
                    { 172, "PA", "Panama", "PAN", 507 },
                    { 173, "PG", "Papua New Guinea", "PNG", 675 },
                    { 174, "PY", "Paraguay", "PRY", 595 },
                    { 175, "PE", "Peru", "PER", 51 },
                    { 176, "PH", "Philippines", "PHL", 63 },
                    { 177, "PN", "Pitcairn", "PCN", 64 },
                    { 178, "PL", "Poland", "POL", 48 },
                    { 179, "PT", "Portugal", "PRT", 351 },
                    { 180, "PR", "Puerto Rico", "PRI", 1787 },
                    { 181, "QA", "Qatar", "QAT", 974 },
                    { 182, "RE", "Réunion", "REU", 262 },
                    { 183, "RO", "Romania", "ROU", 40 },
                    { 184, "RU", "Russian Federation", "RUS", 7 },
                    { 185, "RW", "Rwanda", "RWA", 250 },
                    { 186, "BL", "Saint Barthélemy", "BLM", 590 },
                    { 187, "SH", "Saint Helena, Ascension and Tristan da Cunha", "SHN", 290 },
                    { 188, "KN", "Saint Kitts and Nevis", "KNA", 1869 },
                    { 189, "LC", "Saint Lucia", "LCA", 1758 },
                    { 190, "MF", "Saint Martin (French part)", "MAF", 590 },
                    { 191, "PM", "Saint Pierre and Miquelon", "SPM", 508 },
                    { 192, "VC", "Saint Vincent and the Grenadines", "VCT", 1784 },
                    { 193, "WS", "Samoa", "WSM", 685 },
                    { 194, "SM", "San Marino", "SMR", 378 },
                    { 195, "ST", "Sao Tome and Principe", "STP", 239 },
                    { 196, "SA", "Saudi Arabia", "SAU", 966 },
                    { 197, "SN", "Senegal", "SEN", 221 },
                    { 198, "RS", "Serbia", "SRB", 381 },
                    { 199, "SC", "Seychelles", "SYC", 248 },
                    { 200, "SL", "Sierra Leone", "SLE", 232 },
                    { 201, "SG", "Singapore", "SGP", 65 },
                    { 202, "SX", "Sint Maarten (Dutch part)", "SXM", 1721 },
                    { 203, "SK", "Slovakia", "SVK", 421 },
                    { 204, "SI", "Slovenia", "SVN", 386 },
                    { 205, "SB", "Solomon Islands", "SLB", 677 },
                    { 206, "SO", "Somalia", "SOM", 252 },
                    { 207, "ZA", "South Africa", "ZAF", 27 },
                    { 208, "GS", "South Georgia and the South Sandwich Islands", "SGS", 500 },
                    { 209, "SS", "South Sudan", "SSD", 211 },
                    { 210, "ES", "Spain", "ESP", 34 },
                    { 211, "LK", "Sri Lanka", "LKA", 94 },
                    { 212, "SD", "Sudan", "SDN", 249 },
                    { 213, "SR", "Suriname", "SUR", 597 },
                    { 214, "SJ", "Svalbard and Jan Mayen", "SJM", 47 },
                    { 215, "SE", "Sweden", "SWE", 46 },
                    { 216, "CH", "Switzerland", "CHE", 41 },
                    { 217, "SY", "Syrian Arab Republic", "SYR", 963 },
                    { 218, "TW", "Taiwan, Province of China", "TWN", 886 },
                    { 219, "TJ", "Tajikistan", "TJK", 992 },
                    { 220, "TZ", "Tanzania, United Republic of", "TZA", 255 },
                    { 221, "TH", "Thailand", "THA", 66 },
                    { 222, "TL", "Timor-Leste", "TLS", 670 },
                    { 223, "TG", "Togo", "TGO", 228 },
                    { 224, "TK", "Tokelau", "TKL", 690 },
                    { 225, "TO", "Tonga", "TON", 676 },
                    { 226, "TT", "Trinidad and Tobago", "TTO", 1868 },
                    { 227, "TN", "Tunisia", "TUN", 216 },
                    { 228, "TR", "Türkiye", "TUR", 90 },
                    { 229, "TM", "Turkmenistan", "TKM", 993 },
                    { 230, "TC", "Turks and Caicos Islands", "TCA", 1649 },
                    { 231, "TV", "Tuvalu", "TUV", 688 },
                    { 232, "UG", "Uganda", "UGA", 256 },
                    { 233, "UA", "Ukraine", "UKR", 380 },
                    { 234, "AE", "United Arab Emirates", "ARE", 971 },
                    { 235, "GB", "United Kingdom", "GBR", 44 },
                    { 236, "US", "United States", "USA", 1 },
                    { 237, "UM", "United States Minor Outlying Islands", "UMI", 1 },
                    { 238, "UY", "Uruguay", "URY", 598 },
                    { 239, "UZ", "Uzbekistan", "UZB", 998 },
                    { 240, "VU", "Vanuatu", "VUT", 678 },
                    { 241, "VE", "Venezuela", "VEN", 58 },
                    { 242, "VN", "Viet Nam", "VNM", 84 },
                    { 243, "VG", "Virgin Islands, British", "VGB", 1284 },
                    { 244, "VI", "Virgin Islands, U.S.", "VIR", 1340 },
                    { 245, "WF", "Wallis and Futuna", "WLF", 681 },
                    { 246, "EH", "Western Sahara", "ESH", 212 },
                    { 247, "YE", "Yemen", "YEM", 967 },
                    { 248, "ZM", "Zambia", "ZMB", 260 },
                    { 249, "ZW", "Zimbabwe", "ZWE", 263 }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "countries",
                keyColumn: "id",
                keyValues: Enumerable.Range(1, 249).Cast<object>().ToArray()
            );

            migrationBuilder.DropColumn(
                name: "iso",
                table: "countries");

            migrationBuilder.DropColumn(
                name: "iso3",
                table: "countries");

            migrationBuilder.DropColumn(
                name: "phone_code",
                table: "countries");
        }
    }
}
