// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantApp.Data;

#nullable disable

namespace PlantApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213222540_AddPlantedPlaceHistoryTrigger")]
    partial class AddPlantedPlaceHistoryTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspectPlant", b =>
                {
                    b.Property<int>("AspectsId")
                        .HasColumnType("integer")
                        .HasColumnName("aspects_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("AspectsId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("aspect_plant");
                });

            modelBuilder.Entity("ExposurePlant", b =>
                {
                    b.Property<int>("ExposuresId")
                        .HasColumnType("integer")
                        .HasColumnName("exposures_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("ExposuresId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("exposure_plant");
                });

            modelBuilder.Entity("GrowthLogImage", b =>
                {
                    b.Property<int>("GrowthLogsId")
                        .HasColumnType("integer")
                        .HasColumnName("growth_logs_id");

                    b.Property<int>("ImagesId")
                        .HasColumnType("integer")
                        .HasColumnName("images_id");

                    b.HasKey("GrowthLogsId", "ImagesId");

                    b.HasIndex("ImagesId");

                    b.ToTable("growth_log_image");
                });

            modelBuilder.Entity("GrowthLogPlanted", b =>
                {
                    b.Property<int>("GrowthLogsId")
                        .HasColumnType("integer")
                        .HasColumnName("growth_logs_id");

                    b.Property<int>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.HasKey("GrowthLogsId", "PlantedId");

                    b.HasIndex("PlantedId");

                    b.ToTable("growth_log_planted");
                });

            modelBuilder.Entity("HabitPlant", b =>
                {
                    b.Property<int>("HabitsId")
                        .HasColumnType("integer")
                        .HasColumnName("habits_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("HabitsId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("habit_plant");
                });

            modelBuilder.Entity("ImagePlant", b =>
                {
                    b.Property<int>("ImagesId")
                        .HasColumnType("integer")
                        .HasColumnName("images_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("ImagesId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("image_plant");
                });

            modelBuilder.Entity("ImagePlantExchange", b =>
                {
                    b.Property<int>("ImagesId")
                        .HasColumnType("integer")
                        .HasColumnName("images_id");

                    b.Property<int>("PlantExchangesId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_exchanges_id");

                    b.HasKey("ImagesId", "PlantExchangesId");

                    b.HasIndex("PlantExchangesId");

                    b.ToTable("image_plant_exchange");
                });

            modelBuilder.Entity("ImagePlanted", b =>
                {
                    b.Property<int>("ImagesId")
                        .HasColumnType("integer")
                        .HasColumnName("images_id");

                    b.Property<int>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.HasKey("ImagesId", "PlantedId");

                    b.HasIndex("PlantedId");

                    b.ToTable("image_planted");
                });

            modelBuilder.Entity("MoisturePlant", b =>
                {
                    b.Property<int>("MoisturesId")
                        .HasColumnType("integer")
                        .HasColumnName("moistures_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("MoisturesId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("moisture_plant");
                });

            modelBuilder.Entity("PhPlant", b =>
                {
                    b.Property<int>("PhsId")
                        .HasColumnType("integer")
                        .HasColumnName("phs_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("PhsId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("ph_plant");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Aspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("aspects");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Categories.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("frequencies");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Categories.PlantAttributeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("plant_attribute_types");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Categories.PlantSeasonAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("colour");

                    b.Property<int>("PlantAttributeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_attribute_type_id");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.HasKey("Id");

                    b.HasIndex("PlantAttributeTypeId");

                    b.HasIndex("PlantId");

                    b.HasIndex("SeasonId");

                    b.ToTable("plant_season_attributes");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Categories.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("seasons");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Iso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iso");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iso3");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PhoneCode")
                        .HasColumnType("integer")
                        .HasColumnName("phone_code");

                    b.HasKey("Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.ExchangeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("exchange_types");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Exposure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("exposures");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Fragrance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("fragrances");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.GrowthLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateOnly>("ObservationDate")
                        .HasColumnType("date")
                        .HasColumnName("observation_date");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<int?>("PlantGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_group_id");

                    b.Property<int>("PlantStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PlantGroupId");

                    b.HasIndex("PlantStatusId");

                    b.ToTable("growth_logs");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("habits");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.HardinessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.HasKey("Id");

                    b.ToTable("hardiness_levels");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.HeightType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MaxHeight")
                        .HasColumnType("numeric")
                        .HasColumnName("max_height");

                    b.Property<decimal>("MinHeight")
                        .HasColumnType("numeric")
                        .HasColumnName("min_height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("height_types");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Copyright")
                        .HasColumnType("text")
                        .HasColumnName("copyright");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Moisture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("moistures");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Ph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("phs");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("HumidityIntensity")
                        .HasColumnType("integer")
                        .HasColumnName("humidity_intensity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("SunlightIntensity")
                        .HasColumnType("integer")
                        .HasColumnName("sunlight_intensity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("places");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlaceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<int>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PlantedId");

                    b.ToTable("place_history");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BotanicalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("botanical_name");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cultivation")
                        .HasColumnType("text")
                        .HasColumnName("cultivation");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiseaseResistance")
                        .HasColumnType("text")
                        .HasColumnName("disease_resistance");

                    b.Property<string>("EntityDescription")
                        .HasColumnType("text")
                        .HasColumnName("entity_description");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("family_id");

                    b.Property<int?>("FragranceId")
                        .HasColumnType("integer")
                        .HasColumnName("fragrance_id");

                    b.Property<string>("GenusDescription")
                        .HasColumnType("text")
                        .HasColumnName("genus_description");

                    b.Property<int?>("HardinessLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("hardiness_level_id");

                    b.Property<int?>("HeightTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("height_type_id");

                    b.Property<bool?>("IsDroughtResistant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_drought_resistant");

                    b.Property<bool?>("IsGenus")
                        .HasColumnType("boolean")
                        .HasColumnName("is_genus");

                    b.Property<bool?>("IsLowMaintenance")
                        .HasColumnType("boolean")
                        .HasColumnName("is_low_maintenance");

                    b.Property<bool?>("IsPlantForPollinators")
                        .HasColumnType("boolean")
                        .HasColumnName("is_plant_for_pollinators");

                    b.Property<bool?>("IsSpecie")
                        .HasColumnType("boolean")
                        .HasColumnName("is_specie");

                    b.Property<string>("PestResistance")
                        .HasColumnType("text")
                        .HasColumnName("pest_resistance");

                    b.Property<int?>("PlantAttributeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_attribute_type_id");

                    b.Property<string>("Propagation")
                        .HasColumnType("text")
                        .HasColumnName("propagation");

                    b.Property<string>("Pruning")
                        .HasColumnType("text")
                        .HasColumnName("pruning");

                    b.Property<int?>("SpreadTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("spread_type_id");

                    b.Property<int?>("SynonymParentPlantId")
                        .HasColumnType("integer")
                        .HasColumnName("synonym_parent_plant_id");

                    b.Property<int>("TimeToFullHeightId")
                        .HasColumnType("integer")
                        .HasColumnName("time_to_full_height_id");

                    b.Property<string>("Toxicity")
                        .HasColumnType("text")
                        .HasColumnName("toxicity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("FragranceId");

                    b.HasIndex("HardinessLevelId");

                    b.HasIndex("HeightTypeId");

                    b.HasIndex("PlantAttributeTypeId");

                    b.HasIndex("SpreadTypeId");

                    b.HasIndex("SynonymParentPlantId");

                    b.HasIndex("TimeToFullHeightId");

                    b.ToTable("plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExchangeFor")
                        .HasColumnType("text")
                        .HasColumnName("exchange_for");

                    b.Property<int>("ExchangeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("exchange_type_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MainImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("main_image");

                    b.Property<string>("PlantStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plant_status");

                    b.Property<int?>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Shipping")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ExchangeTypeId");

                    b.HasIndex("PlantedId");

                    b.HasIndex("UserId");

                    b.ToTable("plant_exchanges");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("plant_families");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("plant_groups");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("plant_statuses");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Planted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfDeath")
                        .HasColumnType("date")
                        .HasColumnName("date_of_death");

                    b.Property<DateOnly>("DatePlanted")
                        .HasColumnType("date")
                        .HasColumnName("date_planted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsOutside")
                        .HasColumnType("boolean")
                        .HasColumnName("is_outside");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<int?>("PlantGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_group_id");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<int>("PlantStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_status_id");

                    b.Property<int?>("ReasonOfDeathId")
                        .HasColumnType("integer")
                        .HasColumnName("reason_of_death_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PlantGroupId");

                    b.HasIndex("PlantId");

                    b.HasIndex("PlantStatusId");

                    b.HasIndex("ReasonOfDeathId");

                    b.ToTable("planteds");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.ReasonOfDeath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("reasons_of_death");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_time");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FrequencyNum")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_num");

                    b.Property<int>("FrequencyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_type_id");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_date");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("OriginalDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_due_date");

                    b.Property<int>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.Property<int>("ReminderTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyTypeId");

                    b.HasIndex("PlantedId");

                    b.HasIndex("ReminderTypeId");

                    b.ToTable("reminders");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.ReminderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateDone")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_done");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int>("FrequencyNum")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_num");

                    b.Property<int>("FrequencyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_type_id");

                    b.Property<int?>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.Property<int>("ReminderTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("delay")
                        .HasColumnType("integer")
                        .HasColumnName("delay");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyTypeId");

                    b.HasIndex("PlantedId");

                    b.HasIndex("ReminderTypeId");

                    b.ToTable("reminder_history");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.ReminderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("reminder_types");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.SoilType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("soils");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.SpreadType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MaxSpread")
                        .HasColumnType("numeric")
                        .HasColumnName("max_spread");

                    b.Property<decimal>("MinSpread")
                        .HasColumnType("numeric")
                        .HasColumnName("min_spread");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("spreads");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Sunlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("sunlights");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.TimeToFullHeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxTime")
                        .HasColumnType("integer")
                        .HasColumnName("max_time");

                    b.Property<int>("MinTime")
                        .HasColumnType("integer")
                        .HasColumnName("min_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("time_to_full_height");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.UserRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("RatedId")
                        .HasColumnType("integer")
                        .HasColumnName("rated_id");

                    b.Property<int>("RaterId")
                        .HasColumnType("integer")
                        .HasColumnName("rater_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RatedId");

                    b.HasIndex("RaterId");

                    b.ToTable("user_ratings");
                });

            modelBuilder.Entity("PlantSeason", b =>
                {
                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.Property<int>("SeasonsId")
                        .HasColumnType("integer")
                        .HasColumnName("seasons_id");

                    b.HasKey("PlantsId", "SeasonsId");

                    b.HasIndex("SeasonsId");

                    b.ToTable("plant_season");
                });

            modelBuilder.Entity("PlantSoilType", b =>
                {
                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.Property<int>("SoilTypesId")
                        .HasColumnType("integer")
                        .HasColumnName("soil_types_id");

                    b.HasKey("PlantsId", "SoilTypesId");

                    b.HasIndex("SoilTypesId");

                    b.ToTable("plant_soil_type");
                });

            modelBuilder.Entity("PlantSunlight", b =>
                {
                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.Property<int>("SunlightsId")
                        .HasColumnType("integer")
                        .HasColumnName("sunlights_id");

                    b.HasKey("PlantsId", "SunlightsId");

                    b.HasIndex("SunlightsId");

                    b.ToTable("plant_sunlight");
                });

            modelBuilder.Entity("AspectPlant", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Aspect", null)
                        .WithMany()
                        .HasForeignKey("AspectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExposurePlant", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Exposure", null)
                        .WithMany()
                        .HasForeignKey("ExposuresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrowthLogImage", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.GrowthLog", null)
                        .WithMany()
                        .HasForeignKey("GrowthLogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrowthLogPlanted", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.GrowthLog", null)
                        .WithMany()
                        .HasForeignKey("GrowthLogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Planted", null)
                        .WithMany()
                        .HasForeignKey("PlantedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HabitPlant", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Habit", null)
                        .WithMany()
                        .HasForeignKey("HabitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImagePlant", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImagePlantExchange", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.PlantExchange", null)
                        .WithMany()
                        .HasForeignKey("PlantExchangesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImagePlanted", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Planted", null)
                        .WithMany()
                        .HasForeignKey("PlantedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoisturePlant", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Moisture", null)
                        .WithMany()
                        .HasForeignKey("MoisturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhPlant", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Ph", null)
                        .WithMany()
                        .HasForeignKey("PhsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Categories.PlantSeasonAttribute", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Categories.PlantAttributeType", "PlantAttributeType")
                        .WithMany()
                        .HasForeignKey("PlantAttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Plant", "Plant")
                        .WithMany("PlantSeasonAttributes")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Categories.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("PlantAttributeType");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.City", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.GrowthLog", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Place", "Place")
                        .WithMany("GrowthLogs")
                        .HasForeignKey("PlaceId");

                    b.HasOne("PlantApp.Domain.Models.PlantGroup", "PlantGroup")
                        .WithMany("GrowthLogs")
                        .HasForeignKey("PlantGroupId");

                    b.HasOne("PlantApp.Domain.Models.PlantStatus", "PlantStatus")
                        .WithMany("GrowthLogList")
                        .HasForeignKey("PlantStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("PlantGroup");

                    b.Navigation("PlantStatus");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Image", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.User", "User")
                        .WithMany("UploadedImages")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Place", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.User", "User")
                        .WithMany("Places")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlaceHistory", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Planted", "Planted")
                        .WithMany("PlaceHistory")
                        .HasForeignKey("PlantedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Planted");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Plant", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.PlantFamily", "Family")
                        .WithMany("Plants")
                        .HasForeignKey("FamilyId");

                    b.HasOne("PlantApp.Domain.Models.Fragrance", "Fragrance")
                        .WithMany("Plants")
                        .HasForeignKey("FragranceId");

                    b.HasOne("PlantApp.Domain.Models.HardinessLevel", "HardinessLevel")
                        .WithMany("Plants")
                        .HasForeignKey("HardinessLevelId");

                    b.HasOne("PlantApp.Domain.Models.HeightType", "HeightType")
                        .WithMany("Plants")
                        .HasForeignKey("HeightTypeId");

                    b.HasOne("PlantApp.Domain.Models.Categories.PlantAttributeType", null)
                        .WithMany("Plants")
                        .HasForeignKey("PlantAttributeTypeId");

                    b.HasOne("PlantApp.Domain.Models.SpreadType", "SpreadType")
                        .WithMany("Plants")
                        .HasForeignKey("SpreadTypeId");

                    b.HasOne("PlantApp.Domain.Models.Plant", "SynonymParentPlant")
                        .WithMany("Synonyms")
                        .HasForeignKey("SynonymParentPlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantApp.Domain.Models.TimeToFullHeight", "TimeToFullHeight")
                        .WithMany("Plants")
                        .HasForeignKey("TimeToFullHeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Fragrance");

                    b.Navigation("HardinessLevel");

                    b.Navigation("HeightType");

                    b.Navigation("SpreadType");

                    b.Navigation("SynonymParentPlant");

                    b.Navigation("TimeToFullHeight");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantExchange", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.ExchangeType", "ExchangeType")
                        .WithMany("PlantExchanges")
                        .HasForeignKey("ExchangeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Planted", "Planted")
                        .WithMany()
                        .HasForeignKey("PlantedId");

                    b.HasOne("PlantApp.Domain.Models.User", "User")
                        .WithMany("PlantExchanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("ExchangeType");

                    b.Navigation("Planted");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantGroup", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Planted", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Place", "Place")
                        .WithMany("PlantedList")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.PlantGroup", "PlantGroup")
                        .WithMany("PlantedList")
                        .HasForeignKey("PlantGroupId");

                    b.HasOne("PlantApp.Domain.Models.Plant", "Plant")
                        .WithMany("PlantedList")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.PlantStatus", "PlantStatus")
                        .WithMany("PlantedList")
                        .HasForeignKey("PlantStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.ReasonOfDeath", null)
                        .WithMany("Plants")
                        .HasForeignKey("ReasonOfDeathId");

                    b.Navigation("Place");

                    b.Navigation("Plant");

                    b.Navigation("PlantGroup");

                    b.Navigation("PlantStatus");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Reminder", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Categories.Frequency", "FrequencyType")
                        .WithMany("Reminders")
                        .HasForeignKey("FrequencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Planted", "Planted")
                        .WithMany("Reminders")
                        .HasForeignKey("PlantedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.ReminderType", "ReminderType")
                        .WithMany("Reminders")
                        .HasForeignKey("ReminderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrequencyType");

                    b.Navigation("Planted");

                    b.Navigation("ReminderType");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.ReminderHistory", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Categories.Frequency", "FrequencyType")
                        .WithMany("ReminderHistory")
                        .HasForeignKey("FrequencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Planted", "Planted")
                        .WithMany("ReminderHistory")
                        .HasForeignKey("PlantedId");

                    b.HasOne("PlantApp.Domain.Models.ReminderType", "ReminderType")
                        .WithMany("ReminderHistory")
                        .HasForeignKey("ReminderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FrequencyType");

                    b.Navigation("Planted");

                    b.Navigation("ReminderType");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.User", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.UserRating", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.User", "Rated")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("RatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.User", "Rater")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("RaterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rated");

                    b.Navigation("Rater");
                });

            modelBuilder.Entity("PlantSeason", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Categories.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantSoilType", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.SoilType", null)
                        .WithMany()
                        .HasForeignKey("SoilTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantSunlight", b =>
                {
                    b.HasOne("PlantApp.Domain.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Domain.Models.Sunlight", null)
                        .WithMany()
                        .HasForeignKey("SunlightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Categories.Frequency", b =>
                {
                    b.Navigation("ReminderHistory");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Categories.PlantAttributeType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.ExchangeType", b =>
                {
                    b.Navigation("PlantExchanges");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Fragrance", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.HardinessLevel", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.HeightType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Place", b =>
                {
                    b.Navigation("GrowthLogs");

                    b.Navigation("PlantedList");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Plant", b =>
                {
                    b.Navigation("PlantSeasonAttributes");

                    b.Navigation("PlantedList");

                    b.Navigation("Synonyms");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantFamily", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantGroup", b =>
                {
                    b.Navigation("GrowthLogs");

                    b.Navigation("PlantedList");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.PlantStatus", b =>
                {
                    b.Navigation("GrowthLogList");

                    b.Navigation("PlantedList");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Planted", b =>
                {
                    b.Navigation("PlaceHistory");

                    b.Navigation("ReminderHistory");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.ReasonOfDeath", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.ReminderType", b =>
                {
                    b.Navigation("ReminderHistory");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.SpreadType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.TimeToFullHeight", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Domain.Models.User", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("PlantExchanges");

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");

                    b.Navigation("UploadedImages");
                });
#pragma warning restore 612, 618
        }
    }
}
