// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantApp.Data;

#nullable disable

namespace PlantApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspectPlant", b =>
                {
                    b.Property<int>("AspectsId")
                        .HasColumnType("integer")
                        .HasColumnName("aspects_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("AspectsId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("aspect_plant", (string)null);
                });

            modelBuilder.Entity("ExposurePlant", b =>
                {
                    b.Property<int>("ExposuresId")
                        .HasColumnType("integer")
                        .HasColumnName("exposures_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("ExposuresId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("exposure_plant", (string)null);
                });

            modelBuilder.Entity("GrowthLogImage", b =>
                {
                    b.Property<int>("GrowthLogsId")
                        .HasColumnType("integer")
                        .HasColumnName("growth_logs_id");

                    b.Property<int>("ImagesId")
                        .HasColumnType("integer")
                        .HasColumnName("images_id");

                    b.HasKey("GrowthLogsId", "ImagesId");

                    b.HasIndex("ImagesId");

                    b.ToTable("growth_log_image", (string)null);
                });

            modelBuilder.Entity("HabitPlant", b =>
                {
                    b.Property<int>("HabitsId")
                        .HasColumnType("integer")
                        .HasColumnName("habits_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("HabitsId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("habit_plant", (string)null);
                });

            modelBuilder.Entity("ImagePlant", b =>
                {
                    b.Property<int>("ImagesId")
                        .HasColumnType("integer")
                        .HasColumnName("images_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("ImagesId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("image_plant", (string)null);
                });

            modelBuilder.Entity("ImagePlantExchange", b =>
                {
                    b.Property<int>("ImagesId")
                        .HasColumnType("integer")
                        .HasColumnName("images_id");

                    b.Property<int>("PlantExchangesId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_exchanges_id");

                    b.HasKey("ImagesId", "PlantExchangesId");

                    b.HasIndex("PlantExchangesId");

                    b.ToTable("image_plant_exchange", (string)null);
                });

            modelBuilder.Entity("MoisturePlant", b =>
                {
                    b.Property<int>("MoisturesId")
                        .HasColumnType("integer")
                        .HasColumnName("moistures_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("MoisturesId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("moisture_plant", (string)null);
                });

            modelBuilder.Entity("PhPlant", b =>
                {
                    b.Property<int>("PhsId")
                        .HasColumnType("integer")
                        .HasColumnName("phs_id");

                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.HasKey("PhsId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("ph_plant", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Aspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("aspects", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Categories.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.ExchangeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("exchange_types", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Exposure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("exposures", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Fragrance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("fragrances", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.GrowthLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PlantStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_status_id");

                    b.Property<int>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlantStatusId");

                    b.HasIndex("PlantedId");

                    b.ToTable("growth_logs", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("habits", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.HardinessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.HasKey("Id");

                    b.ToTable("hardiness_levels", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.HeightType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MaxHeight")
                        .HasColumnType("numeric")
                        .HasColumnName("max_height");

                    b.Property<decimal>("MinHeight")
                        .HasColumnType("numeric")
                        .HasColumnName("min_height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("height_types", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Copyright")
                        .HasColumnType("text")
                        .HasColumnName("copyright");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlantedId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Moisture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("moistures", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Ph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("phs", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BotanicalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("botanical_name");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cultivation")
                        .HasColumnType("text")
                        .HasColumnName("cultivation");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiseaseResistance")
                        .HasColumnType("text")
                        .HasColumnName("disease_resistance");

                    b.Property<string>("EntityDescription")
                        .HasColumnType("text")
                        .HasColumnName("entity_description");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("family_id");

                    b.Property<int?>("FragranceId")
                        .HasColumnType("integer")
                        .HasColumnName("fragrance_id");

                    b.Property<string>("GenusDescription")
                        .HasColumnType("text")
                        .HasColumnName("genus_description");

                    b.Property<int?>("HardinessLevelId")
                        .HasColumnType("integer")
                        .HasColumnName("hardiness_level_id");

                    b.Property<int?>("HeightTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("height_type_id");

                    b.Property<bool?>("IsDroughtResistant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_drought_resistant");

                    b.Property<bool?>("IsGenus")
                        .HasColumnType("boolean")
                        .HasColumnName("is_genus");

                    b.Property<bool?>("IsLowMaintenance")
                        .HasColumnType("boolean")
                        .HasColumnName("is_low_maintenance");

                    b.Property<bool?>("IsPlantForPollinators")
                        .HasColumnType("boolean")
                        .HasColumnName("is_plant_for_pollinators");

                    b.Property<bool?>("IsSpecie")
                        .HasColumnType("boolean")
                        .HasColumnName("is_specie");

                    b.Property<string>("PestResistance")
                        .HasColumnType("text")
                        .HasColumnName("pest_resistance");

                    b.Property<string>("Propagation")
                        .HasColumnType("text")
                        .HasColumnName("propagation");

                    b.Property<string>("Pruning")
                        .HasColumnType("text")
                        .HasColumnName("pruning");

                    b.Property<int?>("SpreadTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("spread_type_id");

                    b.Property<int?>("SynonymParentPlantId")
                        .HasColumnType("integer")
                        .HasColumnName("synonym_parent_plant_id");

                    b.Property<int>("TimeToFullHeightId")
                        .HasColumnType("integer")
                        .HasColumnName("time_to_full_height_id");

                    b.Property<string>("Toxicity")
                        .HasColumnType("text")
                        .HasColumnName("toxicity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("FragranceId");

                    b.HasIndex("HardinessLevelId");

                    b.HasIndex("HeightTypeId");

                    b.HasIndex("SpreadTypeId");

                    b.HasIndex("SynonymParentPlantId");

                    b.HasIndex("TimeToFullHeightId");

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.PlantExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExchangeFor")
                        .HasColumnType("text")
                        .HasColumnName("exchange_for");

                    b.Property<int>("ExchangeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("exchange_type_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MainImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("main_image");

                    b.Property<string>("PlantStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plant_status");

                    b.Property<int?>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Shipping")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ExchangeTypeId");

                    b.HasIndex("PlantedId");

                    b.HasIndex("UserId");

                    b.ToTable("plant_exchanges", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.PlantFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("plant_families", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.PlantStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("plant_statuses", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Planted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DatePlanted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_planted");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsOutside")
                        .HasColumnType("boolean")
                        .HasColumnName("is_outside");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<int>("PlantStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_status_id");

                    b.Property<int?>("ReasonOfDeathId")
                        .HasColumnType("integer")
                        .HasColumnName("reason_of_death_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PlantId");

                    b.HasIndex("PlantStatusId");

                    b.HasIndex("ReasonOfDeathId");

                    b.ToTable("planteds", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.ReasonOfDeath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("reasons_of_death", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<DateTime>("NexDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nex_due_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PlantedId")
                        .HasColumnType("integer")
                        .HasColumnName("planted_id");

                    b.Property<int>("ReminderTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlantedId");

                    b.HasIndex("ReminderTypeId");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.ReminderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("reminder_types", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.SoilType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("soils", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.SpreadType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MaxSpread")
                        .HasColumnType("numeric")
                        .HasColumnName("max_spread");

                    b.Property<decimal>("MinSpread")
                        .HasColumnType("numeric")
                        .HasColumnName("min_spread");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("spreads", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.Sunlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("sunlights", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.TimeToFullHeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxTime")
                        .HasColumnType("integer")
                        .HasColumnName("max_time");

                    b.Property<int>("MinTime")
                        .HasColumnType("integer")
                        .HasColumnName("min_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("time_to_full_height", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PlantApp.Data.Models.UserRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PlantExchangeId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_exchange_id");

                    b.Property<int>("RatedId")
                        .HasColumnType("integer")
                        .HasColumnName("rated_id");

                    b.Property<int>("RaterId")
                        .HasColumnType("integer")
                        .HasColumnName("rater_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PlantExchangeId");

                    b.HasIndex("RatedId");

                    b.HasIndex("RaterId");

                    b.ToTable("user_ratings", (string)null);
                });

            modelBuilder.Entity("PlantSeason", b =>
                {
                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.Property<int>("SeasonsId")
                        .HasColumnType("integer")
                        .HasColumnName("seasons_id");

                    b.HasKey("PlantsId", "SeasonsId");

                    b.HasIndex("SeasonsId");

                    b.ToTable("plant_season", (string)null);
                });

            modelBuilder.Entity("PlantSoilType", b =>
                {
                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.Property<int>("SoilTypesId")
                        .HasColumnType("integer")
                        .HasColumnName("soil_types_id");

                    b.HasKey("PlantsId", "SoilTypesId");

                    b.HasIndex("SoilTypesId");

                    b.ToTable("plant_soil_type", (string)null);
                });

            modelBuilder.Entity("PlantSunlight", b =>
                {
                    b.Property<int>("PlantsId")
                        .HasColumnType("integer")
                        .HasColumnName("plants_id");

                    b.Property<int>("SunlightsId")
                        .HasColumnType("integer")
                        .HasColumnName("sunlights_id");

                    b.HasKey("PlantsId", "SunlightsId");

                    b.HasIndex("SunlightsId");

                    b.ToTable("plant_sunlight", (string)null);
                });

            modelBuilder.Entity("AspectPlant", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Aspect", null)
                        .WithMany()
                        .HasForeignKey("AspectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExposurePlant", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Exposure", null)
                        .WithMany()
                        .HasForeignKey("ExposuresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrowthLogImage", b =>
                {
                    b.HasOne("PlantApp.Data.Models.GrowthLog", null)
                        .WithMany()
                        .HasForeignKey("GrowthLogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HabitPlant", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Habit", null)
                        .WithMany()
                        .HasForeignKey("HabitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImagePlant", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImagePlantExchange", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.PlantExchange", null)
                        .WithMany()
                        .HasForeignKey("PlantExchangesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoisturePlant", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Moisture", null)
                        .WithMany()
                        .HasForeignKey("MoisturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhPlant", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Ph", null)
                        .WithMany()
                        .HasForeignKey("PhsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantApp.Data.Models.City", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PlantApp.Data.Models.GrowthLog", b =>
                {
                    b.HasOne("PlantApp.Data.Models.PlantStatus", "PlantStatus")
                        .WithMany("GrowthLogList")
                        .HasForeignKey("PlantStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Planted", "Planted")
                        .WithMany("GrowthLogs")
                        .HasForeignKey("PlantedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantStatus");

                    b.Navigation("Planted");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Image", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Planted", null)
                        .WithMany("Images")
                        .HasForeignKey("PlantedId");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Place", b =>
                {
                    b.HasOne("PlantApp.Data.Models.City", null)
                        .WithMany("Places")
                        .HasForeignKey("CityId");

                    b.HasOne("PlantApp.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.User", "User")
                        .WithMany("Places")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Plant", b =>
                {
                    b.HasOne("PlantApp.Data.Models.PlantFamily", "Family")
                        .WithMany("Plants")
                        .HasForeignKey("FamilyId");

                    b.HasOne("PlantApp.Data.Models.Fragrance", "Fragrance")
                        .WithMany("Plants")
                        .HasForeignKey("FragranceId");

                    b.HasOne("PlantApp.Data.Models.HardinessLevel", "HardinessLevel")
                        .WithMany("Plants")
                        .HasForeignKey("HardinessLevelId");

                    b.HasOne("PlantApp.Data.Models.HeightType", "HeightType")
                        .WithMany("Plants")
                        .HasForeignKey("HeightTypeId");

                    b.HasOne("PlantApp.Data.Models.SpreadType", "SpreadType")
                        .WithMany("Plants")
                        .HasForeignKey("SpreadTypeId");

                    b.HasOne("PlantApp.Data.Models.Plant", "SynonymParentPlant")
                        .WithMany()
                        .HasForeignKey("SynonymParentPlantId");

                    b.HasOne("PlantApp.Data.Models.TimeToFullHeight", "TimeToFullHeight")
                        .WithMany("Plants")
                        .HasForeignKey("TimeToFullHeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Fragrance");

                    b.Navigation("HardinessLevel");

                    b.Navigation("HeightType");

                    b.Navigation("SpreadType");

                    b.Navigation("SynonymParentPlant");

                    b.Navigation("TimeToFullHeight");
                });

            modelBuilder.Entity("PlantApp.Data.Models.PlantExchange", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.ExchangeType", "ExchangeType")
                        .WithMany("PlantExchanges")
                        .HasForeignKey("ExchangeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Planted", "Planted")
                        .WithMany()
                        .HasForeignKey("PlantedId");

                    b.HasOne("PlantApp.Data.Models.User", "User")
                        .WithMany("PlantExchanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("ExchangeType");

                    b.Navigation("Planted");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Planted", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Place", "Place")
                        .WithMany("PlantedList")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Plant", "Plant")
                        .WithMany("PlantedList")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.PlantStatus", "PlantStatus")
                        .WithMany("PlantedList")
                        .HasForeignKey("PlantStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.ReasonOfDeath", null)
                        .WithMany("Plants")
                        .HasForeignKey("ReasonOfDeathId");

                    b.Navigation("Place");

                    b.Navigation("Plant");

                    b.Navigation("PlantStatus");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Reminder", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Planted", "Planted")
                        .WithMany("Reminders")
                        .HasForeignKey("PlantedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.ReminderType", "ReminderType")
                        .WithMany("Reminders")
                        .HasForeignKey("ReminderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planted");

                    b.Navigation("ReminderType");
                });

            modelBuilder.Entity("PlantApp.Data.Models.User", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PlantApp.Data.Models.UserRating", b =>
                {
                    b.HasOne("PlantApp.Data.Models.PlantExchange", "PlantExchange")
                        .WithMany("UserRatings")
                        .HasForeignKey("PlantExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.User", "Rated")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("RatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.User", "Rater")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("RaterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantExchange");

                    b.Navigation("Rated");

                    b.Navigation("Rater");
                });

            modelBuilder.Entity("PlantSeason", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Categories.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantSoilType", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.SoilType", null)
                        .WithMany()
                        .HasForeignKey("SoilTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantSunlight", b =>
                {
                    b.HasOne("PlantApp.Data.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantApp.Data.Models.Sunlight", null)
                        .WithMany()
                        .HasForeignKey("SunlightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantApp.Data.Models.City", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("PlantApp.Data.Models.ExchangeType", b =>
                {
                    b.Navigation("PlantExchanges");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Fragrance", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Data.Models.HardinessLevel", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Data.Models.HeightType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Place", b =>
                {
                    b.Navigation("PlantedList");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Plant", b =>
                {
                    b.Navigation("PlantedList");
                });

            modelBuilder.Entity("PlantApp.Data.Models.PlantExchange", b =>
                {
                    b.Navigation("UserRatings");
                });

            modelBuilder.Entity("PlantApp.Data.Models.PlantFamily", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Data.Models.PlantStatus", b =>
                {
                    b.Navigation("GrowthLogList");

                    b.Navigation("PlantedList");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Planted", b =>
                {
                    b.Navigation("GrowthLogs");

                    b.Navigation("Images");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("PlantApp.Data.Models.ReasonOfDeath", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Data.Models.ReminderType", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("PlantApp.Data.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PlantApp.Data.Models.SpreadType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Data.Models.TimeToFullHeight", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantApp.Data.Models.User", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("PlantExchanges");

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");
                });
#pragma warning restore 612, 618
        }
    }
}
